### ISSUE TITLE
std::any doesnt exist!

### ISSUE THREAD

**Issue by vicollo128** [Megabyte918/QuadTree-Cpp#1]

**Comment by m-byte918** [comment]
Make sure you compile the project with C++17, which is the earliest version that supports `std::any`. You can also replace all occurrences with `void*` to achieve the same effect if you'd rather not switch versions.

**Comment by vicollo128** [comment]
How?

**Comment by m-byte918** [comment]
Specify the library version using the `-std=c++17` compiler flag.

**Comment by vicollo128** [comment]
i mean, how use void*

**Comment by m-byte918** [comment]
Replace all occurrences of `std::any` with `void*`, then cast it to your desired type when you want to use it.

**Comment by vicollo128** [comment]
doesnt work
